name = "Garter Client"
author = "Justin Garter"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9883094b527e2e851f0b7ab303a7157e1f8eb55fb1f7b824ae5c75197a01519d"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
