name = "Garter Client"
author = "Justin Garter"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7325e0dd10976fcf19f4bdf6c3353f1fba321a8fa2a896422c020cecaa1cd0b4"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
